{% set name = "pytorch-pretrained-bert" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: f30ae5d19a95b64bd7068170640608cc457488948aa7643855aa261c2c8ab8b7

build:
  skip: True  # [not linux or py<35]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pytorch-pretrained-bert=pytorch_pretrained_bert.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytorch >=0.4.1
    - numpy
    - boto3
    - requests
    - tqdm

test:
  imports:
    - pytorch_pretrained_bert

about:
  home: https://pypi.org/project/pytorch-pretrained-bert/
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "A PyTorch implementation of Google AI's BERT model provided with Google's pre-trained models, examples and utilities."
  description: |
    This repository contains an op-for-op PyTorch reimplementation of Google's TensorFlow repository for the BERT model that was released together with the paper BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding by Jacob Devlin, Ming-Wei Chang, Kenton Lee and Kristina Toutanova. This implementation is provided with Google's pre-trained models, examples, notebooks and a command-line interface to load any pre-trained TensorFlow checkpoint for BERT is also provided.
  doc_url: https://github.com/huggingface/pytorch-pretrained-BERT
  dev_url: https://github.com/huggingface/pytorch-pretrained-BERT

extra:
  recipe-maintainers:
    - CurtLH
    - sodre
