appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AVDCoYNcvJKSaJ9dEhKqr5P5yXRZ3G5md0dv8VbMWE3yHTGb0fmxAzNGylZ+u+l/kWvykLikfaT60baVdhrtIAtrr0k+CJdWqzEeJ+E2y36WlSncCdMmRrfxdgzx/Jo+bpkw571+yxDIrxWl5ojxFKrFdxAxx1yVng663ve0IO8AylojK0WYOf3erZXK5yYOwmvjf2B0CkbPLcQWRKZ838+H15gJ6Yms2sIXFG/RnHlydUioMzhuWYQksZnQQ+6j8HSdjPJRnfK7m0LYHCur4V5kGxkwUINZTY0GhwFbjGaPI0864Njpypbb/L4VuaGcHqTJaTfiGb4Pea3C6+5Lq3M2ygQgigjlRZVlv0Nk5p/bv2L0wn+tnhHuv226eg3CIvfk1Lvh35sZEDFnsFLy285ormL3TWM7dY1FL6iWTm7PZHEzAVLn8Sv/Ro62/dU3YGKmykrar/71RPxch8DFvAVv0Ll2FdIsjdOzj0+xNhd27nZU3imbM/7SLjWoj6clYI7nYCQRhvJ6U/4hCzbW/mjoGuf3OPYTqQTiK2T3fmX9K1P54MRfciETGxy3lFCW0CR2xtqzCRNbFo4tn/ZozBxjOLVuLw1rOgUSfOcI7hclE0uj90RjBm1S3RIlhWV4Yj3Btw8lSfYjkeB1AktuA2VTtbusTQOzsHVF8rL1oxE=}
